---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: k8s-config
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers: []
          securityContext:
            fsGroup: 2000
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: "xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v1.2.1"
  runtimeConfigRef:
    name: k8s-config
